#!/bin/bash

# Deploy blue version
echo "Deploying blue version..."
kubectl apply -f blue_deployment.yaml

# Deploy green version
echo "Deploying green version..."
kubectl apply -f green_deployment.yaml

# Deploy services
echo "Deploying services..."
kubectl apply -f kubeservice.yaml

# Check logs for green version to detect errors
echo "Checking logs for green version..."
GREEN_POD=$(kubectl get pods -l app=messaging-app,version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
